### ISSUE TITLE
serviceaccount cannot get resource "secrets"

### ISSUE THREAD

**Issue by tschale** [unikubehq/manifests#42]
When trying to `deck install` the cli reports following:
```
[ERROR] Could not load manifest: 500 Server Error: Internal Server Error for url: https://api.unikube.io/manifests/bf781c62-00bc-4ed4-b7a2-b89a7b3c5157
```

The manifest service has following stacktrace:
```
Error: template: consentservice/charts/postgresql/templates/NOTES.txt:82:11: executing "consentservice/charts/postgresql/templates/NOTES.txt" at <include "postgresql.password" .>: error calling include: template: consentservice/charts/postgresql/templates/_helpers.tpl:88:8: executing "postgresql.password" at <include "getValueFromSecret" (dict "Namespace" .Release.Namespace "Name" (include "common.names.fullname" .) "Length" 10 "Key" "postgresql-password")>: error calling include: template: consentservice/charts/postgresql/templates/_helpers.tpl:58:13: executing "getValueFromSecret" at <lookup "v1" "Secret" .Namespace .Name>: error calling lookup: secrets "consentservice-postgresql" is forbidden: User "system:serviceaccount:unikube:unikube-platform-serviceaccount" cannot get resource "secrets" in API group "" in the namespace "consentservice"

[helm-secrets] Removed: /tmp/tmp0udp2df0/consentservice/helm_vars/development/secrets.development.yaml.dec

Error: plugin "secrets" exited with error

Error: plugin "multivalues" exited with error

[2022-06-20 16:17:22 +0000] [14] [ERROR] Exception occurred while handling uri: 'http://api.unikube.io/bf781c62-00bc-4ed4-b7a2-b89a7b3c5157'

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sanic/app.py", line 931, in handle_request
    response = await response
  File "/app/manifests/generator.py", line 115, in generate_manifests
    result = parser.render((deck, render_environment))
  File "/usr/local/lib/python3.8/site-packages/commons/helm/parser.py", line 182, in render
    specs = self.read_specs_data(repo.working_dir, deck, environment)
  File "/usr/local/lib/python3.8/site-packages/commons/helm/parser.py", line 206, in read_specs_data
    with HelmCharts(repository_directory=temp_dir, deck=deck, environment=environment) as kube_files_dir:
  File "/usr/local/lib/python3.8/site-packages/commons/helm/context_manager.py", line 55, in __enter__
    raise HelmChartRenderError(process.stdout.read())
commons.helm.exceptions.HelmChartRenderError
```

The deck can be install manually via helm.

**Comment by tschale** [comment]
The same problem shows up on another project, again with postgres. Both use the bitnami postgres charts v10.16.2

**Comment by buschNT** [comment]
I have the same problem with the buzzword-counter: https://github.com/Blueshoe/buzzword-counter

**Comment by Schille** [comment]
I upgraded Helm in Version 0.8.2. Now it works again.
